## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE)
opt <- options()
options(continue="  ", width=70, prompt=" ")
on.exit(options(opt))
library(iDOVE, quietly=TRUE)

## ----eval=FALSE---------------------------------------------------------------
#  intCens(entry_time, left_time, right_time, vaccination_time)

## ----eval=FALSE---------------------------------------------------------------
#  idove(formula, data, constantVE = FALSE, rightCens = FALSE, plots = TRUE,
#        changePts = NULL, timePts = NULL, tol = 0.0001, maxit = 2000)

## ----eval=FALSE---------------------------------------------------------------
#  intCens(entry_time, left_time, right_time, vaccination_time) ~ covariates

## -----------------------------------------------------------------------------
data(idoveData)

## -----------------------------------------------------------------------------
head(idoveData)

## -----------------------------------------------------------------------------
summary(idoveData)
summary(idoveData$right.time[is.finite(idoveData$right.time)])

## ----fig.align='center', fig.cap='\\label{fig:idoveFigs}Plots auto-generated by \\textit{idove()}. On the left, the estimated curve of vaccine efficacy in reducing the attack rate, $VE_a(t)$ (black) and its $95\\%$ confidence intervals (green) are shown as a function of the time since vaccination. On the right, the estimated curve of vaccine efficacy in reducing the hazard rate, $VE_h(t)$ (black) and its $95\\%$ confidence intervals (green) are shown as a function of the time since vaccination.', echo=TRUE----
model <- intCens(entry.time, left.time, right.time, vaccine.time) ~ priority + sex
result1 <- idove(formula = model, 
                 data = idoveData,
                 changePts = 4*7,
                 timePts = c(4, 16, 28, 40)*7)

## -----------------------------------------------------------------------------
result1$call

## -----------------------------------------------------------------------------
result1$covariates

## -----------------------------------------------------------------------------
result1$vaccine$VE_a
result1$vaccine$VE_h

## -----------------------------------------------------------------------------
result1$vaccine$VE_period

## ----fig.show='hide', eval=FALSE----------------------------------------------
#  plot(x = result1)

## -----------------------------------------------------------------------------
result2 <- idove(formula = model, 
                 data = idoveData,
                 constantVE = TRUE)

## -----------------------------------------------------------------------------
result2$covariates

## -----------------------------------------------------------------------------
result2$vaccine$VE

