# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BS <- function(t, knots, constantVE) {
    .Call('_iDOVE_BS', PACKAGE = 'iDOVE', t, knots, constantVE)
}

EM <- function(w, beta, gamma, lambda, L, R, Rstar, t, tind, X, S, knots, constantVE, threshold = 10^(-4), maxit = 5000L) {
    invisible(.Call('_iDOVE_EM', PACKAGE = 'iDOVE', w, beta, gamma, lambda, L, R, Rstar, t, tind, X, S, knots, constantVE, threshold, maxit))
}

LL <- function(beta, gamma, lambda, L, R, t, tind, X, S, knots, constantVE) {
    .Call('_iDOVE_LL', PACKAGE = 'iDOVE', beta, gamma, lambda, L, R, t, tind, X, S, knots, constantVE)
}

PLL <- function(w, beta, gamma, lambda_init, L, R, Rstar, t, tind, X, S, knots, constantVE, threshold = 10^(-4), maxit = 5000L) {
    .Call('_iDOVE_PLL', PACKAGE = 'iDOVE', w, beta, gamma, lambda_init, L, R, Rstar, t, tind, X, S, knots, constantVE, threshold, maxit)
}

EM_noX <- function(w, gamma, lambda, L, R, Rstar, t, tind, S, knots, constantVE, threshold = 10^(-4), maxit = 5000L) {
    invisible(.Call('_iDOVE_EM_noX', PACKAGE = 'iDOVE', w, gamma, lambda, L, R, Rstar, t, tind, S, knots, constantVE, threshold, maxit))
}

LL_noX <- function(gamma, lambda, L, R, t, tind, S, knots, constantVE) {
    .Call('_iDOVE_LL_noX', PACKAGE = 'iDOVE', gamma, lambda, L, R, t, tind, S, knots, constantVE)
}

PLL_noX <- function(w, gamma, lambda_init, L, R, Rstar, t, tind, S, knots, constantVE, threshold = 10^(-4), maxit = 5000L) {
    .Call('_iDOVE_PLL_noX', PACKAGE = 'iDOVE', w, gamma, lambda_init, L, R, Rstar, t, tind, S, knots, constantVE, threshold, maxit)
}

Init <- function(L, Rstar, W, t) {
    .Call('_iDOVE_Init', PACKAGE = 'iDOVE', L, Rstar, W, t)
}

